SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

-- garanta que está na PDB
ALTER SESSION SET CONTAINER = FREEPDB1;

DECLARE
  v_cnt INTEGER := 0;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM all_users WHERE username = 'ORCL_USER';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER ORCL_USER IDENTIFIED BY ORCL_PWD';
  END IF;

  -- privilégios mínimos para conectar e trabalhar
  EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO ORCL_USER';
  EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO ORCL_USER';
  EXECUTE IMMEDIATE 'ALTER USER ORCL_USER QUOTA UNLIMITED ON USERS';

  -- Se quiser quase admin, descomente:
  -- EXECUTE IMMEDIATE ''GRANT DBA TO ORCL_USER'';
END;
/