--------------------------------------------------------
--  DDL for Table CLIENTE_ACOMP
--------------------------------------------------------

  CREATE TABLE "ORCL_USER"."CLIENTE_ACOMP" 
   (	"ID_CLIENTE" NUMBER(20,0), 
	"STATUS" VARCHAR2(100 CHAR), 
	"SUBSTATUS" VARCHAR2(100 CHAR), 
	"OBS" VARCHAR2(2000 CHAR), 
	"ATUALIZADO_EM" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ORCL_USER"."CLIENTE_ACOMP"."ATUALIZADO_EM" IS 'Última atualização do registro';
   COMMENT ON TABLE "ORCL_USER"."CLIENTE_ACOMP"  IS 'Acompanhamento de clientes (CDC por ATUALIZADO_EM)';
--------------------------------------------------------
--  DDL for Index PK_CLIENTE_ACOMP
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORCL_USER"."PK_CLIENTE_ACOMP" ON "ORCL_USER"."CLIENTE_ACOMP" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_CLIENTE_ACOMP_ATUALIZADO_EM
--------------------------------------------------------

  CREATE INDEX "ORCL_USER"."IDX_CLIENTE_ACOMP_ATUALIZADO_EM" ON "ORCL_USER"."CLIENTE_ACOMP" ("ATUALIZADO_EM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CLIENTE_ACOMP
--------------------------------------------------------

  ALTER TABLE "ORCL_USER"."CLIENTE_ACOMP" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "ORCL_USER"."CLIENTE_ACOMP" MODIFY ("ATUALIZADO_EM" NOT NULL ENABLE);
  ALTER TABLE "ORCL_USER"."CLIENTE_ACOMP" ADD CONSTRAINT "PK_CLIENTE_ACOMP" PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;

  INSERT INTO ORCL_USER.CLIENTE_ACOMP (ID_CLIENTE, STATUS, SUBSTATUS, OBS, ATUALIZADO_EM)
VALUES (1, 'ATIVO', 'OK', 'cliente ativo', SYSTIMESTAMP - INTERVAL '1' DAY);

INSERT INTO ORCL_USER.CLIENTE_ACOMP (ID_CLIENTE, STATUS, SUBSTATUS, OBS, ATUALIZADO_EM)
VALUES (2, 'ATIVO', 'PENDENTE', 'aguardando docs', SYSTIMESTAMP);
COMMIT;
